spring:
  application:
    name: gestorcitasconsultaclinicaspring
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: rodrigo73714089ubnt
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false
